defaults:
  - _model_type_validation  # Validate model type. Defined in /src/utils/config/model.py
  - _self_

name: DT
instance:
  _target_: sklearn.tree.DecisionTreeClassifier
params:
  criterion:
    - gini
    - entropy
  max_depth:
    - !!null
    - 5
    - 10
    - 50
  min_samples_split:
    - 2
    - 4
    - 6
  min_samples_leaf:
    - 1
    - 2
    - 4
  random_state: [] # to be inherited from train config
trainer:
  _target_: model.traditional_ml.train.train_model